[package]
version = "0.1.0"
name = "hdl-register-wizard"
repository = "https://github.com/daixiwen/hdl-register-wizard"
authors = ["Sylvain Tertois <sylvain-gith@becoz.org>"]
description = "App Description"
categories = ["vhdl", "code-generation", "documentation-generation"]
license = "MIT"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies]
# This commit points to Seed 0.7.0 with important fixes.
# Replace with `seed = "0.8.0"` (or newer) once released.
seed = { git = "https://github.com/seed-rs/seed", rev = "0a538f0" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.59"
wasm-bindgen-futures = "0.4.18"
strum = "0.19.5"
strum_macros = "0.19.4"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
