[package]
version = "0.1.0"
name = "hdl_register_wizard"
repository = "https://github.com/daixiwen/hdl-register-wizard"
authors = ["Sylvain Tertois <sylvain-gith@becoz.org>"]
description = "Register HDL code generator wizard"
categories = ["vhdl", "code-generation", "documentation-generation"]
license = "MIT"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.15.0" # Gives us egui, epi and web+native backends
serde = { version = "1.0.116", features = ["derive"],  optional = true }
serde_json = "1.0.59"
strum = "0.19.5"
strum_macros = "0.19.4"
#getrandom = { version = "0.2", features = ["js"] }
#rand = "0.8.0"

[features]
default = ["persistence"]
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown

[profile.release]
#lto = true
#opt-level = 'z'
#codegen-units = 1
opt-level = 2 # fast and small wasm

