name: compile

on:
  push:
    tags:
      - '*'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release --target x86_64-pc-windows-msvc --verbose

      - name: MSI
        run: createmsi.bat
        working-directory: ./install

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: install/hdlregisterwizard.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
