name: develmsi

on: workflow_dispatch

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release --target x86_64-pc-windows-msvc --verbose

      - name: MSI
        run: 
          createmsi.bat
          mkdir dist
          copy hdlregisterwizard.msi dist
        working-directory: ./install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./install/dist
