name: flatpak

on:
  push:
    tags:
      - '*'

jobs:
  build-flatpak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install flatpak
        run: sudo apt-get install flatpak-builder

      - name: create flatpak
        run: install/flatpak/build.sh ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
